name: Notify Webhook on Commit

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  call_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Get Changed Files
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only HEAD~1 HEAD | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      - name: Call Webhook with File Changes
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "author": "${{ github.event.pusher.name }}",
              "message": "${{ github.event.head_commit.message }}",
              "timestamp": "${{ github.event.head_commit.timestamp }}",
              "changed_files": ${{ env.changed_files }}
            }'
